spring.application.name=edualerta

spring.datasource.url=jdbc:mysql://localhost:3306/colegio_qr?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Oniquen_1720
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080